server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1522/FREEPDB1
    username: system
    password: HealthPass123!
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update # Hibernate will now successfully create the PATIENTS table
    show-sql: true
    properties:
      hibernate:
        format_sql: true